some new stuff, mostly cd can take multiple arguments (segments of the path, tries hard along the way); i decided against using scold/attempt fns in order to keep each script portable, but they exist now

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,6 +2,19 @@
 # bashrc/functions
 #
 
+# cry foul
+# (print to stderr)
+# 2019-09-19
+scold () {
+  echo "$*" 1>&2
+}
+
+# don't cry over spilled milk
+# 2019-09-19
+attempt () {
+  $@ 2>/dev/null
+}
+
 # tryhard ()
 #
 # tryhard mode: activated
@@ -237,6 +250,7 @@ EOF
 
 inception () {
   local SHLVL=$(($SHLVL - 1))
+  [[ $TERM == xterm ]] && SHLVL=$(($SHLVL - 2))
   (( $SHLVL == 0 )) || echo "$SHLVL>"
   return $SHLVL
 }
@@ -251,7 +265,7 @@ inception () {
 # Forwards exit code of last executed command
 # prints the code and an error message if not 0
 #
-# Usage: $ <TEST_CMD> ; ok? [MESSAGE...]
+# Usage: $ <TEST_CMD> ; ok [MESSAGE...]
 #
 # cutejs (Astrid Fesz-Nguyen)
 # 2019-01-21
@@ -286,7 +300,9 @@ is_tty () {
 #
 # one of those rare, mysterious 800MB CDs you can never find anymore
 #
-# Usage: drop in replacement for cd
+# Usage: cd [directories...]
+# If omitted, goes to home directory
+# Otherwise treats each word as a segment running prefix before attempting each segment. Fails fast, any bad segment will cause it to return to starting PWD.
 #
 # Environment: Relies on $_CD_MOD_PRE and $_CD_MOD_POST variables
 # for configuration. Prefixes cd+ command with PRE variable @-expanded
@@ -294,29 +310,56 @@ is_tty () {
 #
 # cutejs (Astrid Fesz-Nguyen)
 # 2019-02-15
+# updated 2019-09-19
 
 cd+ () {
+  local -a DEST
   local -a PRE
   local -a POST
-  local DEST=~
-  [[ $1 ]] && DEST="$1"
+  local FAILED=0
+  local OLDERPWD="$OLDPWD"
+  local OLD_PWD="$PWD"
+  if (( $# )); then
+    DEST=("$@")
+  else
+    DEST=("$HOME")
+  fi
   [[ _CD_MOD_PRE ]] && PRE+=(${_CD_MOD_PRE[@]})
   [[ _CD_MOD_POST ]] && POST+=(${_CD_MOD_POST[@]})
 
-  ${PRE[@]} cd "$DEST" && {
+  # run prefix on each segment of path
+  for SEG in ${DEST[@]} ; do
+    # fail fast
+    (( $FAILED )) || {
+      ${PRE[@]} cd "$SEG"
+      FAILED=$?
+    }
+  done
+
+  # go back if something went wrong
+  if (( $FAILED )); then
+    OLDPWD="$OLDERPWD"
+    cd "$OLD_PWD"
+    echo "You can't get there from here" 1>&2
+    return 127
+  # run post commands
+  else
     local -a CMD
-    local DONE=
+    local ERROR=
     for FRAG in ${POST[@]} ; do
       if [[ "$FRAG" != '--' ]] ; then
         CMD+=("$FRAG")
       else
-        ${CMD[@]} || DONE=$?
-        [[ $DONE ]] && return $DONE
+        # run command
+        ${CMD[@]} || ERROR=$?
+        [[ $ERROR ]] && return $ERROR
+        # make room for next command
         CMD=()
       fi
     done
-  [[ $CMD ]] && ${CMD[@]}
-  } 
+    # final remaining command
+    [[ $CMD ]] && ${CMD[@]}
+  fi
 }
 
 #
@@ -404,51 +447,35 @@ cat_or_ls () {
   fi
 }
 
+# oh bash, you know what I meant
 vim_or_cd () {
   if [[ ! $1 ]]; then
-  $EDITOR
-  elif [[ -f $1 ]]; then
-    $EDITOR "$@"
+    $EDITOR
   elif [[ -d $1 ]]; then
-  cd+ $1
+    cd+ $1
   else
-    echo "$1: Not a file or directory" 1>&2
-    return 127
+    $EDITOR "$@"
   fi
 }
 
+# you know me all too well
 cd_or_vim () {
   if [[ ! $1 ]]; then
-  cd+
+    cd+
   elif [[ -f $1 ]]; then
     $EDITOR "$@"
   else
-  cd+ "$1"
+    cd+ "$@"
   fi
-}
-
-lib () {
-  local FOUND=`\
-    tryhard -r ls lib 2>/dev/null ||\
-    tryhard -U ls lib 2>/dev/null ||\
-  `
-  [[ $FOUND ]] && cd $FOUND
-}
-
-src () {
-  local FOUND=`\
-    tryhard -r ls src 2>/dev/null ||\
-    tryhard -U ls src 2>/dev/null ||\
-  `
-  [[ $FOUND ]] && cd $FOUND
 }
 
 #(Disc|C)harging, 
 
 _bat_match () {
-  [[ `acpi -i` =~ (Discharging|Charging|Unknown|Not charging),\ ([0-9]{1,3})%.*(remaining|until\ charged|.) ]]
+  [[ `attempt acpi -i` =~ (Discharging|Charging|Unknown|Not charging),\ ([0-9]{1,3})%.*(remaining|until\ charged|.) ]]
 }
 
+# used in my terminal prompt. The @ sign is a battery indicator ^_^
 batcolor () {
   _bat_match
   local CHARGE=${BASH_REMATCH[1]}
@@ -458,17 +485,17 @@ batcolor () {
   [[ $BASH_REMATCH ]] && {
     if [[ $CHARGE == Discharging ]]; then
       if (( $NUM <= 10 )); then
-        COLOR=$'\033[1;31m'
+        COLOR=$'\033[1;31m' # Critical = red
       elif (( $NUM <= 42 )); then
-        COLOR=$'\033[1;33m'
+        COLOR=$'\033[1;33m' # Warning = yellow
       else
-        COLOR=$'\033[1;32m'
+        COLOR=$'\033[1;32m' # Still Good = green
       fi
     elif [[ $CHARGE == 'Unknown' ]]; then
-      COLOR=$'\033[0;35m'
+      COLOR=$'\033[0;34m' # Unknown = purple
     else
-      if (( $NUM <= 75 )); then
-        COLOR=$'\033[1;34m'
+      if (( $NUM <= 85 )); then
+        COLOR=$'\033[1;34m' # Charging = blue
       fi
     fi
   }
